### PR TITLE
Gitopscon NA 2021 Blog

### PR DESCRIPTION
**Pull request by christianh814**
Added a blog entry about GitOpsCon. Please feel free to edit as I'm prone to make typos.

### CODE REVIEW

**Review by scottrigby — CHANGES_REQUESTED** [review]
Yeah looking good! Only a few things I think would be good before pushing out:
1. List the sponsors and link each back to their company website. Good to do and also gives everyone incentive to amplify
2. We may want to link directly to the schedule https://events.linuxfoundation.org/gitopscon-north-america/program/schedule/

**Review by todaywasawesome — APPROVED** [review]
Looks good!

**Review by scottrigby — APPROVED** [review]
👍✨👍

**Comment by todaywasawesome** [comment]
Excellent, thanks @scottrigby

**Pull request merged**
