### PR TITLE
Feat: Add new training page

### PR DESCRIPTION
**Pull request by thisisobate**
Fixes https://github.com/cncf/techdocs/issues/214

### CODE REVIEW

**Comment by thisisobate** [comment]
cc: @todaywasawesome @niklasmtj @nate-double-u

**Review by todaywasawesome — APPROVED** [review]
LGTM

**Comment by nate-double-u** [comment]
I'm getting errors when I try to build, is the README up to date?

```
# if you like npm 
npm i
npm start

# Or if you like yarn
yarn install
yarn start
```

Both throw errors

**Comment by thisisobate** [comment]
It’s weird that both ‘yarn install’ and ‘yarn start’ both throw an error. 

What version of Node are you running?

**Comment by thisisobate** [comment]
Can you share the error message here?

**Comment by nate-double-u** [comment]
Sure, I'm using `nvm` so it's easy to shift the node version if I'm using the wrong one.
```
➜  website git:(uche/training-page) ✗ nvm current
v18.18.2

➜  website git:(uche/training-page) ✗ npm start

> open-git-ops@1.0.0 start
> gatsby develop --host=0.0.0.0

success open and validate gatsby-configs, load plugins - 0.707s
success onPreInit - 0.031s
success initialize cache - 0.020s
success copy gatsby files - 0.061s
⠋ onPreBootstrap
⠋ Compiling Gatsby Functions
/Users/natew-cncf/Repos/open-gitops/website/node_modules/yoga-layout-prebuilt/yoga-layout/build/Release/nbind.js:53
        throw ex;
        ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:69:19)
    at Object.createHash (node:crypto:133:10)
    at BulkUpdateDecorator.hashFactory (/Users/natew-cncf/Repos/open-gitops/website/node_modules/webpack/lib/util/createHash.js:145:18)
    at BulkUpdateDecorator.digest (/Users/natew-cncf/Repos/open-gitops/website/node_modules/webpack/lib/util/createHash.js:80:21)
    at Compilation.createHash (/Users/natew-cncf/Repos/open-gitops/website/node_modules/webpack/lib/Compilation.js:3456:47)
    at /Users/natew-cncf/Repos/open-gitops/website/node_modules/webpack/lib/Compilation.js:2483:39
    at /Users/natew-cncf/Repos/open-gitops/website/node_modules/webpack/lib/Compilation.js:2680:5
    at Object.eachLimit (/Users/natew-cncf/Repos/open-gitops/website/node_modules/neo-async/async.js:3461:14)
    at Compilation._runCodeGenerationJobs (/Users/natew-cncf/Repos/open-gitops/website/node_modules/webpack/lib/Compilation.js:2642:12)
    at Compilation.codeGeneration (/Users/natew-cncf/Repos/open-gitops/website/node_modules/webpack/lib/Compilation.js:2632:8)
    at /Users/natew-cncf/Repos/open-gitops/website/node_modules/webpack/lib/Compilation.js:2468:11
    at Hook.eval [as callAsync] (eval at create (/Users/natew-cncf/Repos/open-gitops/website/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/natew-cncf/Repos/open-gitops/website/node_modules/webpack/node_modules/tapable/lib/Hook.js:18:14)
    at /Users/natew-cncf/Repos/open-gitops/website/node_modules/webpack/lib/Compilation.js:2422:36
    at Hook.eval [as callAsync] (eval at create (/Users/natew-cncf/Repos/open-gitops/website/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/natew-cncf/Repos/open-gitops/website/node_modules/webpack/node_modules/tapable/lib/Hook.js:18:14) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.18.2
```

**Comment by nate-double-u** [comment]
I get the same error with the node lts (v20.12.0)

**Review by nate-double-u — APPROVED** [review]
OK, [found the issue's solution](https://stackoverflow.com/a/70116509), and adding an environment variable to my terminal helped get it running:

```
export NODE_OPTIONS=--openssl-legacy-provider
```

Screenshot 2024-03-26 at 2 54 11 PM

Thanks for this @thisisobate!

/lgtm

**Review by niklasmtj — APPROVED** [review]
This looks cool! Thanks for your PR. 

LGTM

**Pull request merged**
