### PR TITLE
pull request check

### LINKED ISSUE #70: NPM or Yarn? We must choose!
There has been issues ([example](https://github.com/open-gitops/website/runs/5188644224?check_suite_focus=true#step:4:13)) with respect to merging because the doc says that you can use `npm` or `yarn`, but in fact, you can only use `npm`  because that's what the github action is set to only use NPM.

Here are suggestions

* We use either `npm` or `yarn` and update the README to tell users to use the chosen one.
* OR, make the github action "smarter" by taking into account that a user could have used either one.

In any even, we should prevent this issue from happening.

### PR DESCRIPTION
**Pull request by strantalis**
This pr partially resolves #70 by adding a github action to run `npm ci`, `npm lint` and `npm build` on pull requests to do some basic validation that the site can be built.

### CODE REVIEW

**Comment by strantalis** [comment]
@niklasmtj @chris-short @christianh814 I am not that familiar with how github actions caching is supposed to work so looking for a second set of eyes. Maybe I am just missing something. 

When testing [this](https://github.com/open-gitops/website/blob/f0f95e9f7d00363a04e41474ef805ec35625b468/.github/workflows/pr-check.yml) configuration my assumption was I thought I could basically build the cache in the `install` job then carry it over to the `lint` and `build` jobs but that doesn't seem to be the case. 

I might have been over complicating it as well. The below action works if we are okay with a single job (tested on my own repo).

```
name: CI Checks

on:
  pull_request:
    branches:    
      - main

jobs:
  check:
    name: Pull Request Lint/Build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Build
        run: npm run build
```

**Comment by niklasmtj** [comment]
I think that your posted solution above is a good one. Since the steps are run in sequence and not in parallel (as far as I know) as done in the link you posted. For me your steps look fine. We can be sure that a successful run of the Action will give us a proper Gatsby build.

Do you know why `eslint` does not work in the Action? I read everywhere that it is locally preinstalled when using `setup-node` action.

If you need any help going further just hit me up. (Berlin timezone, fyi 😀)

**Review by christianh814 — APPROVED** [review]
This LGTM

**Review by scottrigby — APPROVED** [review]
thank you @strantalis and @niklasmtj ❤️

**Pull request merged**
