### PR TITLE
docs(get-involved.js): Events → Get Involved

### PR DESCRIPTION
**Pull request by lloydchang**
Signed-off-by: lloydchang <lloydchang@gmail.com>

### CODE REVIEW

**Comment by lloydchang** [comment]
Fix https://github.com/open-gitops/website/issues/35

**Review by christianh814 — APPROVED** [review]
/lgtm

**Review by scottrigby — APPROVED** [review]
TY

**Comment by scottrigby** [comment]
This one was also fixed in https://github.com/open-gitops/website/pull/73 which got merged first. Thank you!

**Pull request closed without merging**
